name: Build Docker Images
on:
  schedule:
    # TODO: only run daily
    - cron: '*/30 * * * *'

jobs:
  build-images:
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout heighliner
        uses: actions/checkout@v2

      - name: Build heighliner
        run: go build

      - name: Login to docker
        run: echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USER --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: ./heighliner build -b --buildkit-addr tcp://127.0.0.1:8125 -r ghcr.io/strangelove-ventures/heighliner
        env:
          GITHUB_USER: ${{ secrets.DOCKER_USER }}
          GITHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
